### ISSUE TITLE
Type error with redux-thunk

### ISSUE THREAD

**Issue by brysonandrew** [WhitestormJS/whitestorm-typescript-boilerplate#6]
Very cool boilerplate. Thanks for the time and effort.

I had a typing issue with redux-thunk when running npm start.

I fixed this with replacing 
```javascript
import thunk from 'redux-thunk';
``` 
with  
```javascript
const thunk = require('redux-thunk').default;
````

Now it compiles fine.

**Comment by hirako2000** [comment]
Odd, which version of node?

**Comment by sasha240100** [comment]
@hirako2000 @brysonandrew Looks like an error that can be solved by https://github.com/59naga/babel-plugin-add-module-exports

**Comment by brysonandrew** [comment]
@hirako2000 node version - v9.11.1

@sasha240100 I think you're right there

**Comment by brysonandrew** [comment]
FYI reading this helped me fix it https://github.com/reduxjs/redux-thunk/issues/35

**Comment by hirako2000** [comment]
I've looked into it, I first couldn't reproduce but got a number of compiling issues. I updated a number of libraries, including redux and thunk.
Things are working for me now. If you could pull the latest and confirm, the work-around shouldn't be needed now.

4fb11237fd8e01c20f1c76cc85a5fd657adb737c 81606c8901ad3a21368621eacc56b86518f62aba 30a88750587a989137ed4f0b53ffe7e3b4b62822 95c0206cef8bb618d84de337a65f89b9693f9b83

**Comment by brysonandrew** [comment]
@hirako2000 Nice work, works straight after clone now. Thanks
