### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by brysonandrew** [WhitestormJS/whitestorm-typescript-boilerplate#7]
This isn't really a bug but anyone interested in deploying to heroku will need to do the following steps:

1) In `server.tsx` change the line (45) `app.listen(appConfig.port, appConfig.host, (err) => {` to `app.listen(appConfig.port, (err) => {`

2) In `webpack/prod.js` change the line (38) `filename: 'js/[name].[chunkhash].js'` to `filename: 'js/[name].js'`

The second step may be a bug because when I deploy without it it looks for `public/js/app.some-hash-here.js`. In the build file is only `public/js/app.js`

**Comment by hirako2000** [comment]
We would really welcome a PR :)

**Comment by brysonandrew** [comment]
@hirako2000 PR made with the above changes.

**Comment by hirako2000** [comment]
Merged, thanks @brysonandrew !

**Comment by brysonandrew** [comment]
@hirako2000 Welcome
